"""Local-first trajectory ledger and improvement-engine foundations."""

from .models import (
    EvaluationEvidence,
    Trajectory,
    TrajectoryEvent,
    ValidatorEvidence,
)
from .diagnose import Diagnosis, DiagnosisConfig, DiagnosisProvider, ProviderOutputError, diagnose_trajectories
from .evaluate import (
    ChampionRegistry,
    CandidateResultBundle,
    DeterministicComparisonRunner,
    EvaluationConfig,
    EvaluationError,
    EvaluationRun,
    ReplayStatusValidator,
    evaluate_candidate,
)
from .redaction import RedactionConfig, Redactor
from .compound import (
    CandidateOutcome,
    CompoundConfig,
    CompoundCurator,
    CompoundError,
    CompoundGenerator,
    CompoundReflector,
    CompoundReport,
    CompoundRun,
    build_compound_report,
    compound_trajectories,
    default_compound_report_paths,
    write_compound_report,
)
from .promotion import ApprovalResult, PromotionError, PromotionResult, RollbackResult, approve_candidate, promote_candidate, rollback_candidate
from .retrieval import (
    EmbeddingProvider,
    RetrievalContextItem,
    RetrievalError,
    RetrievalRecord,
    RetrievalResult,
    RetrievalSelection,
    default_retrieval_path,
    retrieve_approved_assets,
    write_retrieval_context,
    write_retrieval_record,
)
from .replay import (
    DeterministicFixtureRunner,
    ReplayCase,
    ReplayError,
    ReplaySuite,
    build_replay_suite,
    run_replay_suite,
)
from .store import IngestResult, LedgerStore, initialize_layout

__all__ = [
    "EvaluationEvidence",
    "Diagnosis",
    "DiagnosisConfig",
    "DiagnosisProvider",
    "ChampionRegistry",
    "ApprovalResult",
    "CandidateResultBundle",
    "DeterministicComparisonRunner",
    "EvaluationConfig",
    "EvaluationError",
    "EvaluationRun",
    "PromotionError",
    "PromotionResult",
    "RollbackResult",
    "IngestResult",
    "LedgerStore",
    "ProviderOutputError",
    "RedactionConfig",
    "Redactor",
    "CandidateOutcome",
    "CompoundConfig",
    "CompoundCurator",
    "CompoundError",
    "CompoundGenerator",
    "CompoundReflector",
    "CompoundReport",
    "CompoundRun",
    "EmbeddingProvider",
    "RetrievalContextItem",
    "RetrievalError",
    "RetrievalRecord",
    "RetrievalResult",
    "RetrievalSelection",
    "ReplayStatusValidator",
    "DeterministicFixtureRunner",
    "ReplayCase",
    "ReplayError",
    "ReplaySuite",
    "Trajectory",
    "TrajectoryEvent",
    "ValidatorEvidence",
    "build_replay_suite",
    "diagnose_trajectories",
    "evaluate_candidate",
    "approve_candidate",
    "initialize_layout",
    "promote_candidate",
    "rollback_candidate",
    "default_retrieval_path",
    "retrieve_approved_assets",
    "write_retrieval_context",
    "write_retrieval_record",
    "build_compound_report",
    "compound_trajectories",
    "default_compound_report_paths",
    "write_compound_report",
    "run_replay_suite",
]

__version__ = "0.1.0"
