export { getDataLayout, parseConfig, SAFE_DEFAULTS } from "./config.js"
export type { DataLayout, LocalMemoryConfig, SubsystemSwitches } from "./config.js"
export { INTERNAL_SESSION_PREFIX, InternalSessionRegistry, readSessionID } from "./internal-session.js"
export { Ledger } from "./capture/ledger.js"
export type { ConsolidationRun, LedgerOptions, LedgerStatus } from "./capture/ledger.js"
export { CapturePolicy } from "./capture/policy.js"
export type { CapturePolicyOptions } from "./capture/policy.js"
export { createLedgerCapturePort } from "./capture/port.js"
export type { CaptureCandidate, CaptureDecision, LedgerEvent, SanitizedCapture, SanitizerAction } from "./capture/types.js"
export { inspectWorkspace, normalizePath } from "./projects/identity.js"
export { ProjectRegistry } from "./projects/registry.js"
export { createProjectListTool } from "./projects/tool.js"
export { RecallService } from "./recall/service.js"
export type { OptionalMemoryAdapter, RecallServiceOptions } from "./recall/service.js"
export { UnifiedRecallPolicy } from "./recall/policy.js"
export type { RecallRecord, RecallRequest, RecallResult, RecallScope, RecallSource, RecallStatus } from "./recall/policy.js"
export { BasicMemoryMarkdownSource, CodememCliSource, assertReadableDirectory } from "./recall/sources.js"
export type { BasicMemoryMarkdownSourceOptions, CodememCliSourceOptions } from "./recall/sources.js"
export { MemoryControlService } from "./controls/service.js"
export { createMemoryControlTools } from "./controls/tools.js"
export { createBackup, restoreBackup } from "./operations.js"
export type { ProjectKind, ProjectRecord, ProjectResolution, ReconciliationPreview, WorkspaceIdentity } from "./projects/types.js"
export { buildConsolidationPrompt, parseAssertions } from "./consolidation/schema.js"
export { createOpenCodeRunner } from "./consolidation/runner.js"
export { ConsolidationService } from "./consolidation/service.js"
export type { AssertionCategory, AssertionProposal, AssertionRecord, ConsolidationInput, ConsolidationRunner } from "./consolidation/types.js"
export type { CapturePort, ConsolidationPort, InjectionPort, MemoryPorts, PluginLogger } from "./ports.js"
export { createLocalMemoryPlugin, LocalMemoryPlugin } from "./plugin.js"
export type { PluginDependencies } from "./plugin.js"
export { SUPPORTED_EVENT_TYPES, readSupportedEventType } from "./supported-events.js"
export { readUpstreamPlugin, UPSTREAM_COMMIT, UPSTREAM_LICENSE, UPSTREAM_REPOSITORY } from "./upstream.js"

export default LocalMemoryPlugin
export const server = LocalMemoryPlugin
import { LocalMemoryPlugin } from "./plugin.js"
